name: testsite2
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63392
title: testsite2
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f2430'
    - '#347fa1'
    - '#23591d'
    - '#809d83'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
